public enum WebErrorCode
{
    OK = 0,
    REGISTER_FAIL_CHARACTER_LIMIT = -100,
    REGISTER_FAIL_PASSWORD_LIMIT = -101,
    REGISTER_FAIL_PIN_LIMIT = -102,
    REGISTER_FAIL_OVERLAP = -103,
    LOGIN_FAIL_ID = -200,
    LOGIN_FAIL_PASSWORD = -201,
}